"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Check, Film, ImagePlus, KeyRound, LoaderCircle, LogOut, Pencil, Play, Plus, Save, Trash2, XCircle, Link2, RefreshCw } from "lucide-react";
import { genres, type FilmOption } from "@/lib/films";
import "./admin.css";

type Movie = FilmOption & { poster?: string | null; sortOrder?: number };
const blank = (): Movie => ({id:"",title:"",year:new Date().getFullYear(),genre:"Terror",wiki:"",poster:"",synopsis:"",trailer:"",emoji:"🎬",tone:"plum"});
export default function Admin() {
  const initialized = useRef(false);
  const driveDirty = useRef(false);
  const [authorized,setAuthorized]=useState(false),[loading,setLoading]=useState(true),[pin,setPin]=useState("");
  const [movies,setMovies]=useState<Movie[]>([]),[selected,setSelected]=useState<string[]>([]),[editing,setEditing]=useState<Movie|null>(null);
  const [active,setActive]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [confirmCancel,setConfirmCancel]=useState(false);
  const [totalVotes,setTotalVotes]=useState(0),[finished,setFinished]=useState(false),[driveUrl,setDriveUrl]=useState<string|null>(null),[driveInput,setDriveInput]=useState("");
  const refresh=useCallback(async()=>{const res=await fetch("/api/admin",{cache:"no-store"});if(res.status===401){setAuthorized(false);setLoading(false);return;}const data=await res.json() as {films:Movie[];activeSession:string|null;totalVotes:number;finished:boolean;driveUrl:string|null;error?:string};if(!res.ok)throw new Error(data.error||"Painel indisponível.");setMovies(data.films);setSelected(prev=>initialized.current?prev.filter(id=>data.films.some((f:Movie)=>f.id===id)):data.films.map((f:Movie)=>f.id));initialized.current=true;setActive(data.activeSession);setTotalVotes(data.totalVotes);setFinished(data.finished);setDriveUrl(data.driveUrl);if(!driveDirty.current)setDriveInput(data.driveUrl||"");setAuthorized(true);setLoading(false);},[]);
  useEffect(()=>{void refresh().catch(()=>{setError("Não foi possível abrir o painel.");setLoading(false);});},[refresh]);
  useEffect(()=>{if(!authorized)return;const timer=setInterval(()=>{void refresh().catch(()=>{});},8000);return()=>clearInterval(timer);},[authorized,refresh]);
  async function action(payload:Record<string,unknown>){const res=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await res.json() as {error?:string;sessionId?:string};if(!res.ok)throw new Error(data.error||"Não foi possível salvar.");return data;}
  async function enter(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await action({action:"login",pin});setPin("");await refresh();}catch(e){setError(e instanceof Error?e.message:"Senha incorreta.");}finally{setBusy(false);}}
  async function save(e:React.FormEvent){e.preventDefault();if(!editing)return;setBusy(true);setError("");try{await action({action:"save-film",film:editing});await refresh();setEditing(null);setNotice("Filme salvo no catálogo.");}catch(e){setError(e instanceof Error?e.message:"Confira os dados do filme.");}finally{setBusy(false);}}
  async function remove(id:string){setBusy(true);setError("");try{await action({action:"delete-film",id});setSelected(x=>x.filter(v=>v!==id));await refresh();setEditing(null);setNotice("Filme removido do catálogo.");}catch(e){setError(e instanceof Error?e.message:"Não foi possível remover.");}finally{setBusy(false);}}
  async function start(){setBusy(true);setError("");try{const data=await action({action:"start",filmIds:selected});setActive(data.sessionId||null);setTotalVotes(0);setFinished(false);setDriveUrl(null);setDriveInput("");driveDirty.current=false;setConfirmCancel(false);setNotice("Sessão iniciada! A votação já está disponível para o grupo.");}catch(e){setError(e instanceof Error?e.message:"Não foi possível iniciar.");}finally{setBusy(false);}}
  async function cancel(){if(!active)return;setBusy(true);setError("");try{await action({action:"cancel",sessionId:active});setActive(null);setTotalVotes(0);setFinished(false);setDriveUrl(null);setDriveInput("");driveDirty.current=false;setConfirmCancel(false);setNotice("Sessão cancelada. O grupo verá a tela de espera até você iniciar outra.");}catch(e){setError(e instanceof Error?e.message:"Não foi possível cancelar.");}finally{setBusy(false);}}
  async function saveDrive(e:React.FormEvent){e.preventDefault();if(!active)return;setBusy(true);setError("");try{await action({action:"set-drive",sessionId:active,driveUrl:driveInput.trim()});driveDirty.current=false;await refresh();setNotice(driveInput.trim()?"Filme liberado para o grupo assistir no site.":"Link do filme removido.");}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar o link.");}finally{setBusy(false);}}
  async function clearDrive(){if(!active)return;setBusy(true);setError("");try{await action({action:"set-drive",sessionId:active,driveUrl:""});driveDirty.current=false;setDriveInput("");await refresh();setNotice("Link do filme removido.");}catch(e){setError(e instanceof Error?e.message:"Não foi possível remover o link.");}finally{setBusy(false);}}
  async function logout(){await action({action:"logout"});initialized.current=false;setAuthorized(false);setEditing(null);}
  const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);
  return <main className="admin-shell"><header className="admin-header"><a href="/" className="admin-logo"><span><Film size={19}/></span><span className="admin-brand-name">CineCar</span><small>PAINEL DE CONTROLE</small></a>{authorized?<button className="admin-quiet" onClick={()=>void logout()}><LogOut size={16}/> Sair</button>:<a className="admin-quiet" href="/"><ArrowLeft size={16}/> Voltar ao site</a>}</header>
    {loading?<div className="admin-loading"><LoaderCircle className="spin"/> Abrindo painel…</div>:!authorized?<section className="admin-login"><div className="admin-badge"><KeyRound size={24}/></div><span className="admin-kicker">ACESSO À CABINE</span><h1>Você comanda<br/><em>a sessão.</em></h1><p>Entre com a senha para escolher os filmes em cartaz e iniciar a próxima votação.</p><form onSubmit={enter}><label htmlFor="pin">Senha do painel</label><input id="pin" type="password" inputMode="numeric" autoComplete="off" maxLength={20} value={pin} onChange={e=>setPin(e.target.value)} placeholder="••••••" required/><button disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<KeyRound size={18}/>} Entrar no painel</button></form>{error&&<p className="admin-error">{error}</p>}</section>:<div className="admin-content"><div className="admin-lede"><div><span className="admin-kicker"><Film size={15}/> PROGRAMAÇÃO DO CINECAR</span><h1>Monte a próxima<br/><em>sessão de cinema.</em></h1><p>Edite o catálogo, marque os filmes em cartaz e abra a votação quando tudo estiver pronto.</p></div><div className="admin-status"><span>SESSÃO ATUAL</span><strong>{active?"No ar":"Ainda não iniciada"}</strong>{active&&<small>{totalVotes} / 3 votos</small>}{active&&<><a href={"/?sessao="+active} target="_blank" rel="noreferrer">Abrir sessão <ArrowRight size={14}/></a>{confirmCancel?<div className="cancel-confirm"><p>Cancelar a sessão para todos?</p><div><button onClick={()=>setConfirmCancel(false)}>Voltar</button><button className="cancel-danger" disabled={busy} onClick={()=>void cancel()}>{busy?<LoaderCircle className="spin" size={14}/>:<XCircle size={14}/>} Confirmar</button></div></div>:<button className="cancel-link" onClick={()=>setConfirmCancel(true)}><XCircle size={14}/> Cancelar sessão</button>}</>}</div></div>
      {notice&&<p className="admin-notice"><Check size={16}/>{notice}</p>}{error&&<p className="admin-error">{error}</p>}
      <section className="admin-slate"><div className="admin-section-heading"><div><span className="admin-kicker">01 / ESCOLHA O CARTAZ</span><h2>Filmes disponíveis <small>{selected.length} selecionados</small></h2></div><button className="admin-add" onClick={()=>{setEditing(blank());setError("");}}><Plus size={17}/> Adicionar filme</button></div>
        <div className="admin-movies">{movies.map(m=><article key={m.id} className={"admin-movie"+(selected.includes(m.id)?" on":"")}><button className="admin-pick" onClick={()=>toggle(m.id)} aria-pressed={selected.includes(m.id)} aria-label={(selected.includes(m.id)?"Remover ":"Selecionar ")+m.title}><span>{selected.includes(m.id)?<Check size={16}/>:null}</span></button><div className="admin-poster">{m.poster?<img src={m.poster} alt={"Cartaz de "+m.title}/>:<span>{m.emoji}</span>}</div><div className="admin-movie-copy"><small>{m.genre} · {m.year}</small><h3>{m.title}</h3><p>{m.synopsis}</p><button className="admin-edit" onClick={()=>{setEditing({...m});setError("");}}><Pencil size={14}/> Editar</button></div></article>)}</div>
      </section>
      <section className="admin-launch"><div><span className="admin-kicker">02 / ABRA AS PORTAS</span><h2>Tudo pronto para a estreia?</h2><p>Ao iniciar, uma nova sessão será aberta com os {selected.length} filmes marcados. O grupo escolhe a data chuvosa e vota.</p></div><button disabled={busy||selected.length<2} onClick={()=>void start()}>{busy?<LoaderCircle className="spin" size={19}/>:<Play size={18} fill="currentColor"/>} Iniciar sessão</button></section>
      {active&&<section className="admin-drive"><div className="admin-drive-title"><div><span className="admin-kicker">03 / HORA DA SESSÃO</span><h2>Filme para assistir</h2></div><button className="admin-quiet" onClick={()=>void refresh()}><RefreshCw size={15}/> Atualizar votos</button></div>{finished?<form onSubmit={saveDrive}><label htmlFor="drive-link">Link do arquivo no Google Drive</label><div className="admin-drive-field"><input id="drive-link" type="url" value={driveInput} onChange={e=>{driveDirty.current=true;setDriveInput(e.target.value);}} placeholder="https://drive.google.com/file/d/.../view"/><button disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<Link2 size={17}/>} {driveUrl?"Atualizar link":"Liberar filme"}</button></div><p>Compartilhe o arquivo no Drive com “Qualquer pessoa com o link” para o grupo conseguir assistir. O player do Drive aparece no resultado com os controles oferecidos pelo Drive.</p>{driveUrl&&<button className="admin-remove-drive" type="button" disabled={busy} onClick={()=>void clearDrive()}>Remover vídeo da sessão</button>}</form>:<p className="admin-drive-locked">O link pode ser adicionado assim que os três amigos votarem. Placar: <b>{totalVotes} / 3</b>.</p>}</section>}
      {editing&&<div className="admin-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setEditing(null);}}><form className="admin-editor" onSubmit={save} aria-label="Editar filme"><div className="admin-editor-top"><div><span className="admin-kicker">CATÁLOGO</span><h2>{editing.id?"Editar filme":"Novo filme"}</h2></div><button type="button" className="admin-close" onClick={()=>setEditing(null)} aria-label="Fechar">×</button></div><div className="admin-form-grid"><label>Nome do filme<input required maxLength={100} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Ano<input required type="number" min="1900" max="2100" value={editing.year} onChange={e=>setEditing({...editing,year:Number(e.target.value)})}/></label><label>Categoria<select value={editing.genre} onChange={e=>setEditing({...editing,genre:e.target.value})}>{genres.map(g=><option key={g}>{g}</option>)}</select></label><label>Link direto da imagem no Imgur <span>(opcional)</span><input type="url" placeholder="https://i.imgur.com/arquivo.jpg" value={editing.poster||""} onChange={e=>setEditing({...editing,poster:e.target.value})}/></label><label className="admin-wide">Sinopse<textarea required minLength={20} maxLength={1200} rows={4} value={editing.synopsis} onChange={e=>setEditing({...editing,synopsis:e.target.value})}/></label><label className="admin-wide">Link do trailer no YouTube<input required type="url" placeholder="https://www.youtube.com/watch?v=..." value={editing.trailer} onChange={e=>setEditing({...editing,trailer:e.target.value})}/></label></div><p className="admin-image-help"><ImagePlus size={16}/> Envie a imagem ao Imgur e cole aqui o link direto que termina em .jpg, .png ou .webp.</p>{error&&<p className="admin-error">{error}</p>}<div className="admin-editor-actions">{editing.id&&<button type="button" className="admin-delete" disabled={busy} onClick={()=>void remove(editing.id)}><Trash2 size={15}/> Excluir</button>}<button type="submit" className="admin-save" disabled={busy}>{busy?<LoaderCircle className="spin" size={16}/>:<Save size={16}/>} Salvar filme</button></div></form></div>}
    </div>}
  </main>;
}
