export type FilmOption = { id: string; title: string; year: number; genre: string; wiki: string; poster?: string | null; synopsis: string; trailer: string; emoji: string; tone: string };

export const starterFilms: FilmOption[] = [
  { id:"shining", title:"O Iluminado", year:1980, genre:"Terror", wiki:"The Shining (film)", synopsis:"Um escritor aceita cuidar de um hotel isolado durante o inverno. O silêncio do lugar e acontecimentos cada vez mais estranhos transformam o trabalho em pesadelo.", trailer:"https://www.youtube.com/watch?v=FZQvIJxG9Xs", emoji:"🪓", tone:"plum" },
  { id:"conjuring", title:"Invocação do Mal", year:2013, genre:"Terror", wiki:"The Conjuring", synopsis:"Dois investigadores paranormais ajudam uma família que enfrenta acontecimentos assustadores em sua nova casa. Terror de clima crescente para ver com a coberta por perto.", trailer:"https://www.youtube.com/watch?v=k10ETZ41q5o", emoji:"🕯️", tone:"violet" },
  { id:"madmax", title:"Mad Max: Estrada da Fúria", year:2015, genre:"Ação", wiki:"Mad Max: Fury Road", synopsis:"Em um deserto devastado, Max se junta a Furiosa numa fuga alucinante por estradas perigosas. Ação quase sem pausa e imagens grandiosas.", trailer:"https://www.youtube.com/watch?v=hEJnMQG9ev8", emoji:"🏎️", tone:"orange" },
  { id:"johnwick", title:"John Wick: De Volta ao Jogo", year:2014, genre:"Ação", wiki:"John Wick (film)", synopsis:"Um ex-assassino tenta viver em paz, mas uma perda inesperada o puxa de volta ao submundo que deixou para trás. Ação coreografada e história direta.", trailer:"https://www.youtube.com/watch?v=2AUmvWm5ZDQ", emoji:"🎯", tone:"blue" },
  { id:"whitechicks", title:"As Branquelas", year:2004, genre:"Comédia", wiki:"White Chicks", synopsis:"Dois agentes do FBI assumem uma missão disfarçados de socialites. A operação sai do controle em uma sequência de situações absurdas e muito humor físico.", trailer:"https://www.youtube.com/watch?v=cBubWQdaBVc", emoji:"😎", tone:"pink" },
  { id:"superbad", title:"Superbad: É Hoje", year:2007, genre:"Comédia", wiki:"Superbad", synopsis:"Dois amigos tentam aproveitar a última grande festa antes da formatura. Uma comédia sobre amizade, planos atrapalhados e a despedida de uma fase.", trailer:"https://www.youtube.com/watch?v=LvKvus3vCEY", emoji:"🎉", tone:"lime" },
  { id:"interstellar", title:"Interestelar", year:2014, genre:"Ficção", wiki:"Interstellar (film)", synopsis:"Com a Terra enfrentando um futuro difícil, uma equipe parte em busca de um novo lar para a humanidade. Uma aventura sobre tempo, distância e família.", trailer:"https://www.youtube.com/watch?v=i6avfCqKcQo", emoji:"🚀", tone:"cyan" },
  { id:"inception", title:"A Origem", year:2010, genre:"Ficção", wiki:"Inception", synopsis:"Um especialista em invadir sonhos recebe a tarefa quase impossível de plantar uma ideia na mente de alguém. Camadas de realidade e reviravoltas para conversar depois.", trailer:"https://www.youtube.com/watch?v=YoHD9XEInc0", emoji:"🌀", tone:"indigo" },
  { id:"spiderverse", title:"Homem-Aranha no Aranhaverso", year:2018, genre:"Animação", wiki:"Spider-Man: Into the Spider-Verse", synopsis:"Miles Morales descobre que pode ser o Homem-Aranha e encontra versões do herói de outros universos. Animação vibrante, humor e aventura para todo mundo.", trailer:"https://www.youtube.com/watch?v=g4Hbz2jLxvQ", emoji:"🕸️", tone:"red" },
  { id:"spiritedaway", title:"A Viagem de Chihiro", year:2001, genre:"Animação", wiki:"Spirited Away", synopsis:"Em um mundo mágico cheio de espíritos, Chihiro precisa encontrar coragem para salvar os pais e voltar para casa. Uma fantasia cheia de imaginação.", trailer:"https://www.youtube.com/watch?v=GAp2_0JJskk", emoji:"🐉", tone:"green" },
];
export const genres = ["Terror", "Ação", "Comédia", "Ficção", "Animação"];
